postgresql:
  host: localhost
  user: tiv
  passwd: tiv
  dbname: tiv
  port: 5432

twitter:
  consumer_key: insert_consumer_key_here
  consumer_secret: insert_consumer_secret_here
  access_token_key: insert_access_token_key_here
  access_token_secret: insert_access_token_secret_here
  screen_name: insert_screen_name_here

twitter-mine:
  mine_followers: True
  mine_tweets: True
  mine_number_of_followers: 3
  mine_tweet_count: 10

gmaps:
  api_key: insert_google_maps_api_key_here
  country: Norway

tweet_storage:
  directory: '/var/www/tweet_dumps'
  default_filename: 'tweet-'
  default_file_extension: 'json'
